FROM ubuntu:latest
RUN apt-get update

# $ docker build -t ubuntu-vv --platform linux/arm64/v8
#! docker run -td --privileged --name viv-ubuntu --restart unless-stopped -e 'TZ=Asiz/Seoul' -p 22:22 -p 53:53 -p 53:53/udp ubuntu-vv:latest /sbin/init
# docker-compose -f dockerfile.yml up -d --no-recreate
# docker commit $ContainerID <ImageName>
